name: Requests To The Universe
favicon: null
layout_spectrum: 0.64691
typography_spectrum: 0.21341
title: How Can You Manifest Your Destiny?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f3cfb9'
    - '#bd7d57'
    - '#000000'
    - '#ab4320'
  brandStrength: 0.16438344470225275
  lightness: 0.787917762529105
  saturation: 0.39428153657354414
  rhythmicContrast: 0.7492182380519807
purpose: []
