name: Requests To The Universe
favicon: null
layout_spectrum: 0.1794574793893844
typography_spectrum: 0.06649863091297448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.16438344470225275
  lightness: 0.787917762529105
  saturation: 0.39428153657354414
  rhythmicContrast: 0.7492182380519807
purpose: []
